const ReachContent = [
	{
		imgSrc: "./img-partnership/logo_ig 2x.webp",
		imgAlt: "Reach IG Riliv",
		imgWidth: "55px",
		Title: "Instagram",
		Reach: "188.000++",
		Description: "followers",
		first: true,
		firstRow: true,
	},
	{
		imgSrc: "./img-partnership/logo_fb 2x.webp",
		imgAlt: "Reach FB Riliv",
		imgWidth: "67px",
		Title: "Facebook",
		Reach: "18.700++",
		Description: "monthly post reach",
		firstRow: true,
	},
	{
		imgSrc: "./img-partnership/logo_twitter 2x.webp",
		imgAlt: "Reach Twitter Riliv",
		imgWidth: "65px",
		Title: "Twitter",
		Reach: "22.000++",
		Description: "monthly engagements",
		firstRow: true,
	},
	{
		imgSrc: "./img-partnership/logo_tiktok 2x.webp",
		imgAlt: "Reach TikTok Riliv",
		imgWidth: "59px",
		Title: "TikTok",
		Reach: "3.400.000++",
		Description: "viewers",
		firstRow: true,
	},
	{
		imgSrc: "./img-partnership/logo_web 2x.webp",
		imgAlt: "Reach Website Riliv",
		imgWidth: "67px",
		Title: "Website Riliv",
		Reach: "335.000++",
		Description: "monthly traffic",
	},
	{
		imgSrc: "./img-partnership/logo_hp 2x.webp",
		imgAlt: "Reach Aplikasi Riliv",
		imgWidth: "52px",
		Title: "Aplikasi Riliv",
		Reach: "200.000++",
		Description: "downloaders",
	},
	{
		imgSrc: "./img-partnership/logo_mail 2x.webp",
		imgAlt: "Reach Email Riliv",
		imgWidth: "76px",
		Title: "Email List",
		Reach: "50.000++",
		Description: "followers",
	},
];
export default ReachContent;
